"""fix user

Revision ID: 5bb5cd591ff5
Revises: 53983ced69fd
Create Date: 2018-10-18 01:12:35.784907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bb5cd591ff5'
down_revision = '53983ced69fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_tag', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('salary_max', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('salary_min', sa.String(length=64), nullable=True))
    op.drop_column('job', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('salary', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('job', 'salary_min')
    op.drop_column('job', 'salary_max')
    op.drop_column('job', 'job_tag')
    # ### end Alembic commands ###
